# Terraform Provider release workflow.
name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  tag_version:
    runs-on: ubuntu-latest
    name: Create tag version on GitHub repository
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3
      - name: Get version from feature branch
        id: get_version
        run: echo "CURRENT_VERSION=v$(cat version)" >> "$GITHUB_ENV"
      - name: Create tag
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ env.CURRENT_VERSION }}
          tag_name: ${{ env.CURRENT_VERSION }}
  goreleaser:
    runs-on: ubuntu-latest
    needs: tag_version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
