name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

permissions:
  contents: write

jobs:
  tag_version:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from feature branch
        id: get_version
        run: echo "CURRENT_VERSION=$(cat version)" >> "$GITHUB_ENV"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          custom_tag: ${{ env.CURRENT_VERSION }}
  goreleaser:
    name: Publish provider
    runs-on: ubuntu-latest
    needs: tag_version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        id: import_gpg
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
